### ISSUE TITLE
QTouch 1.1.3

### ISSUE THREAD

**Issue by ZcheK** [quxios/QMV-Master-Demo#10]
Using plugin command qTouch change default img/cursors/Walk.png
Was working in 1.1.2
All QPlugins up to date.
(Apologies for closing and reopening this, I mistakenly thought I had it working.)
["change", "default", "img/cursors/Walk.png"]
rpg_managers.js:1949 TypeError: undefined is not a function
at Game_Interpreter.pluginCommand (QTouch.js:186)
at Game_Interpreter.pluginCommand (QMap.js:195)
at Game_Interpreter.pluginCommand (QSprite.js:302)
at Game_Interpreter.pluginCommand (QAudio.js:178)
at Game_Interpreter.pluginCommand (QCamera.js:158)
at Game_Interpreter.pluginCommand (QPathfind.js:754)
at Game_Interpreter.pluginCommand (QPopup.js:388)
at Game_Interpreter.pluginCommand (QABS.js:2226)
at Game_Interpreter.pluginCommand (QSight.js:203)
at Game_Interpreter.pluginCommand (QPicture.js:324)

**Comment by quxios** [comment]
Thanks for the report! Just fixed this, will push fix soon
